# Dockerfile.dashboard.j2
FROM python:3.9-bullseye
WORKDIR /app

# Install required packages for pyarrow
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Add the bot file from the build context
ADD {{ bot_file }} /app/{{ bot_file }}

# Install additional packages from requirements.txt
ADD requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir pyarrow==10.0.1 streamlit

# Add the run script
ADD run.sh ./

# Set the PYTHONUNBUFFERED environment variable to ensure real-time output
ENV PYTHONUNBUFFERED=1

# Disable Python's generation of .pyc files
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8501

# Make the run script executable
RUN chmod +x run.sh

# Start the agent and Streamlit dashboard
CMD ["./run.sh"]